// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxmgIHxha-fawLKRk2VMkNTIgA90W9Do4',
    appId: '1:663687544904:web:d24d501ea6b357942d187d',
    messagingSenderId: '663687544904',
    projectId: 'flutterclassproject-2e9b3',
    authDomain: 'flutterclassproject-2e9b3.firebaseapp.com',
    storageBucket: 'flutterclassproject-2e9b3.firebasestorage.app',
    measurementId: 'G-L6Z8PSEBEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxysV7NU0FNKL2nme9PcwcC_h2plAuydw',
    appId: '1:663687544904:android:f9722884cf102ae62d187d',
    messagingSenderId: '663687544904',
    projectId: 'flutterclassproject-2e9b3',
    storageBucket: 'flutterclassproject-2e9b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtHKFZtF-Kk35COcnK76_3V9g2txOP50Y',
    appId: '1:663687544904:ios:dd4ded62df0dbea92d187d',
    messagingSenderId: '663687544904',
    projectId: 'flutterclassproject-2e9b3',
    storageBucket: 'flutterclassproject-2e9b3.firebasestorage.app',
    iosBundleId: 'com.example.cadeschessgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtHKFZtF-Kk35COcnK76_3V9g2txOP50Y',
    appId: '1:663687544904:ios:dd4ded62df0dbea92d187d',
    messagingSenderId: '663687544904',
    projectId: 'flutterclassproject-2e9b3',
    storageBucket: 'flutterclassproject-2e9b3.firebasestorage.app',
    iosBundleId: 'com.example.cadeschessgame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxmgIHxha-fawLKRk2VMkNTIgA90W9Do4',
    appId: '1:663687544904:web:c8898b1d8faddc222d187d',
    messagingSenderId: '663687544904',
    projectId: 'flutterclassproject-2e9b3',
    authDomain: 'flutterclassproject-2e9b3.firebaseapp.com',
    storageBucket: 'flutterclassproject-2e9b3.firebasestorage.app',
    measurementId: 'G-9RYH7LTV0J',
  );
}
